name: CICD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: this is the env where the workflow run
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
    

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Code cloned from GitHub"

  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: Build container
        run: echo "Docker container build"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test container
        run: echo "Testing container"

  deploy:
    if: inputs.environment == 'dev'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy container
        run: echo "Container deployed"
