name: Abhishek
on:
  push:
    branches: [main]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to Abhi
        run: echo "hello dosto"
      - name: say hello to username
        run: echo "hello $Abhi"
  details:
    runs-on: ubuntu-latest
    steps:
      - name: version of python and docker etc...
        run: docker --version && and python --version
